version: '3.7'

services:
  server:
    build:
      context: ./
    container_name: csproject-server
    depends_on:
      - mongo
    networks:
      - "test_network"

  mongo:
    restart: always
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - "test_network"

networks:
  test_network: